"""add otp columns

Revision ID: 4575a3fbf86e
Revises: 0f5e5bbd6732
Create Date: 2021-09-16 21:00:22.456178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4575a3fbf86e'
down_revision = '0f5e5bbd6732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp_secret', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp_secret')
    # ### end Alembic commands ###
